// Code generated by go-swagger; DO NOT EDIT.

package zookeeper

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// StatReader is a Reader for the Stat structure.
type StatReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StatReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStatOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewStatNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewStatInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStatOK creates a StatOK with default headers values
func NewStatOK() *StatOK {
	return &StatOK{}
}

/*StatOK handles this case with default header values.

Success
*/
type StatOK struct {
}

func (o *StatOK) Error() string {
	return fmt.Sprintf("[GET /zk/stat][%d] statOK ", 200)
}

func (o *StatOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStatNotFound creates a StatNotFound with default headers values
func NewStatNotFound() *StatNotFound {
	return &StatNotFound{}
}

/*StatNotFound handles this case with default header values.

Table not found
*/
type StatNotFound struct {
}

func (o *StatNotFound) Error() string {
	return fmt.Sprintf("[GET /zk/stat][%d] statNotFound ", 404)
}

func (o *StatNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStatInternalServerError creates a StatInternalServerError with default headers values
func NewStatInternalServerError() *StatInternalServerError {
	return &StatInternalServerError{}
}

/*StatInternalServerError handles this case with default header values.

Internal server error
*/
type StatInternalServerError struct {
}

func (o *StatInternalServerError) Error() string {
	return fmt.Sprintf("[GET /zk/stat][%d] statInternalServerError ", 500)
}

func (o *StatInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
