// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DropInstanceReader is a Reader for the DropInstance structure.
type DropInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DropInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDropInstanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDropInstanceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewDropInstanceConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDropInstanceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDropInstanceOK creates a DropInstanceOK with default headers values
func NewDropInstanceOK() *DropInstanceOK {
	return &DropInstanceOK{}
}

/*DropInstanceOK handles this case with default header values.

Success
*/
type DropInstanceOK struct {
}

func (o *DropInstanceOK) Error() string {
	return fmt.Sprintf("[DELETE /instances/{instanceName}][%d] dropInstanceOK ", 200)
}

func (o *DropInstanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDropInstanceNotFound creates a DropInstanceNotFound with default headers values
func NewDropInstanceNotFound() *DropInstanceNotFound {
	return &DropInstanceNotFound{}
}

/*DropInstanceNotFound handles this case with default header values.

Instance not found
*/
type DropInstanceNotFound struct {
}

func (o *DropInstanceNotFound) Error() string {
	return fmt.Sprintf("[DELETE /instances/{instanceName}][%d] dropInstanceNotFound ", 404)
}

func (o *DropInstanceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDropInstanceConflict creates a DropInstanceConflict with default headers values
func NewDropInstanceConflict() *DropInstanceConflict {
	return &DropInstanceConflict{}
}

/*DropInstanceConflict handles this case with default header values.

Instance cannot be dropped
*/
type DropInstanceConflict struct {
}

func (o *DropInstanceConflict) Error() string {
	return fmt.Sprintf("[DELETE /instances/{instanceName}][%d] dropInstanceConflict ", 409)
}

func (o *DropInstanceConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDropInstanceInternalServerError creates a DropInstanceInternalServerError with default headers values
func NewDropInstanceInternalServerError() *DropInstanceInternalServerError {
	return &DropInstanceInternalServerError{}
}

/*DropInstanceInternalServerError handles this case with default header values.

Internal error
*/
type DropInstanceInternalServerError struct {
}

func (o *DropInstanceInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /instances/{instanceName}][%d] dropInstanceInternalServerError ", 500)
}

func (o *DropInstanceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
