// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllInstancesParams creates a new GetAllInstancesParams object
// with the default values initialized.
func NewGetAllInstancesParams() *GetAllInstancesParams {

	return &GetAllInstancesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllInstancesParamsWithTimeout creates a new GetAllInstancesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllInstancesParamsWithTimeout(timeout time.Duration) *GetAllInstancesParams {

	return &GetAllInstancesParams{

		timeout: timeout,
	}
}

// NewGetAllInstancesParamsWithContext creates a new GetAllInstancesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllInstancesParamsWithContext(ctx context.Context) *GetAllInstancesParams {

	return &GetAllInstancesParams{

		Context: ctx,
	}
}

// NewGetAllInstancesParamsWithHTTPClient creates a new GetAllInstancesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllInstancesParamsWithHTTPClient(client *http.Client) *GetAllInstancesParams {

	return &GetAllInstancesParams{
		HTTPClient: client,
	}
}

/*GetAllInstancesParams contains all the parameters to send to the API endpoint
for the get all instances operation typically these are written to a http.Request
*/
type GetAllInstancesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all instances params
func (o *GetAllInstancesParams) WithTimeout(timeout time.Duration) *GetAllInstancesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all instances params
func (o *GetAllInstancesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all instances params
func (o *GetAllInstancesParams) WithContext(ctx context.Context) *GetAllInstancesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all instances params
func (o *GetAllInstancesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all instances params
func (o *GetAllInstancesParams) WithHTTPClient(client *http.Client) *GetAllInstancesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all instances params
func (o *GetAllInstancesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllInstancesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
