// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spaghettifunk/pinot-go-client/models"
)

// NewUpdateInstanceParams creates a new UpdateInstanceParams object
// with the default values initialized.
func NewUpdateInstanceParams() *UpdateInstanceParams {
	var ()
	return &UpdateInstanceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateInstanceParamsWithTimeout creates a new UpdateInstanceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateInstanceParamsWithTimeout(timeout time.Duration) *UpdateInstanceParams {
	var ()
	return &UpdateInstanceParams{

		timeout: timeout,
	}
}

// NewUpdateInstanceParamsWithContext creates a new UpdateInstanceParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateInstanceParamsWithContext(ctx context.Context) *UpdateInstanceParams {
	var ()
	return &UpdateInstanceParams{

		Context: ctx,
	}
}

// NewUpdateInstanceParamsWithHTTPClient creates a new UpdateInstanceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateInstanceParamsWithHTTPClient(client *http.Client) *UpdateInstanceParams {
	var ()
	return &UpdateInstanceParams{
		HTTPClient: client,
	}
}

/*UpdateInstanceParams contains all the parameters to send to the API endpoint
for the update instance operation typically these are written to a http.Request
*/
type UpdateInstanceParams struct {

	/*Body*/
	Body *models.Instance
	/*InstanceName
	  Instance name

	*/
	InstanceName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update instance params
func (o *UpdateInstanceParams) WithTimeout(timeout time.Duration) *UpdateInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update instance params
func (o *UpdateInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update instance params
func (o *UpdateInstanceParams) WithContext(ctx context.Context) *UpdateInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update instance params
func (o *UpdateInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update instance params
func (o *UpdateInstanceParams) WithHTTPClient(client *http.Client) *UpdateInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update instance params
func (o *UpdateInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update instance params
func (o *UpdateInstanceParams) WithBody(body *models.Instance) *UpdateInstanceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update instance params
func (o *UpdateInstanceParams) SetBody(body *models.Instance) {
	o.Body = body
}

// WithInstanceName adds the instanceName to the update instance params
func (o *UpdateInstanceParams) WithInstanceName(instanceName string) *UpdateInstanceParams {
	o.SetInstanceName(instanceName)
	return o
}

// SetInstanceName adds the instanceName to the update instance params
func (o *UpdateInstanceParams) SetInstanceName(instanceName string) {
	o.InstanceName = instanceName
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param instanceName
	if err := r.SetPathParam("instanceName", o.InstanceName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
