// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateInstanceTagsReader is a Reader for the UpdateInstanceTags structure.
type UpdateInstanceTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateInstanceTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateInstanceTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewUpdateInstanceTagsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateInstanceTagsOK creates a UpdateInstanceTagsOK with default headers values
func NewUpdateInstanceTagsOK() *UpdateInstanceTagsOK {
	return &UpdateInstanceTagsOK{}
}

/*UpdateInstanceTagsOK handles this case with default header values.

Success
*/
type UpdateInstanceTagsOK struct {
}

func (o *UpdateInstanceTagsOK) Error() string {
	return fmt.Sprintf("[PUT /instances/{instanceName}/updateTags][%d] updateInstanceTagsOK ", 200)
}

func (o *UpdateInstanceTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateInstanceTagsInternalServerError creates a UpdateInstanceTagsInternalServerError with default headers values
func NewUpdateInstanceTagsInternalServerError() *UpdateInstanceTagsInternalServerError {
	return &UpdateInstanceTagsInternalServerError{}
}

/*UpdateInstanceTagsInternalServerError handles this case with default header values.

Internal error
*/
type UpdateInstanceTagsInternalServerError struct {
}

func (o *UpdateInstanceTagsInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /instances/{instanceName}/updateTags][%d] updateInstanceTagsInternalServerError ", 500)
}

func (o *UpdateInstanceTagsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
