// Code generated by go-swagger; DO NOT EDIT.

package schema

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListSchemaNamesParams creates a new ListSchemaNamesParams object
// with the default values initialized.
func NewListSchemaNamesParams() *ListSchemaNamesParams {

	return &ListSchemaNamesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListSchemaNamesParamsWithTimeout creates a new ListSchemaNamesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListSchemaNamesParamsWithTimeout(timeout time.Duration) *ListSchemaNamesParams {

	return &ListSchemaNamesParams{

		timeout: timeout,
	}
}

// NewListSchemaNamesParamsWithContext creates a new ListSchemaNamesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListSchemaNamesParamsWithContext(ctx context.Context) *ListSchemaNamesParams {

	return &ListSchemaNamesParams{

		Context: ctx,
	}
}

// NewListSchemaNamesParamsWithHTTPClient creates a new ListSchemaNamesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListSchemaNamesParamsWithHTTPClient(client *http.Client) *ListSchemaNamesParams {

	return &ListSchemaNamesParams{
		HTTPClient: client,
	}
}

/*ListSchemaNamesParams contains all the parameters to send to the API endpoint
for the list schema names operation typically these are written to a http.Request
*/
type ListSchemaNamesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list schema names params
func (o *ListSchemaNamesParams) WithTimeout(timeout time.Duration) *ListSchemaNamesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list schema names params
func (o *ListSchemaNamesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list schema names params
func (o *ListSchemaNamesParams) WithContext(ctx context.Context) *ListSchemaNamesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list schema names params
func (o *ListSchemaNamesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list schema names params
func (o *ListSchemaNamesParams) WithHTTPClient(client *http.Client) *ListSchemaNamesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list schema names params
func (o *ListSchemaNamesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListSchemaNamesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
