// Code generated by go-swagger; DO NOT EDIT.

package schema

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ValidateSchemaReader is a Reader for the ValidateSchema structure.
type ValidateSchemaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateSchemaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewValidateSchemaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewValidateSchemaBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewValidateSchemaInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewValidateSchemaOK creates a ValidateSchemaOK with default headers values
func NewValidateSchemaOK() *ValidateSchemaOK {
	return &ValidateSchemaOK{}
}

/*ValidateSchemaOK handles this case with default header values.

Successfully validated schema
*/
type ValidateSchemaOK struct {
}

func (o *ValidateSchemaOK) Error() string {
	return fmt.Sprintf("[POST /schemas/validate][%d] validateSchemaOK ", 200)
}

func (o *ValidateSchemaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateSchemaBadRequest creates a ValidateSchemaBadRequest with default headers values
func NewValidateSchemaBadRequest() *ValidateSchemaBadRequest {
	return &ValidateSchemaBadRequest{}
}

/*ValidateSchemaBadRequest handles this case with default header values.

Missing or invalid request body
*/
type ValidateSchemaBadRequest struct {
}

func (o *ValidateSchemaBadRequest) Error() string {
	return fmt.Sprintf("[POST /schemas/validate][%d] validateSchemaBadRequest ", 400)
}

func (o *ValidateSchemaBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateSchemaInternalServerError creates a ValidateSchemaInternalServerError with default headers values
func NewValidateSchemaInternalServerError() *ValidateSchemaInternalServerError {
	return &ValidateSchemaInternalServerError{}
}

/*ValidateSchemaInternalServerError handles this case with default header values.

Internal error
*/
type ValidateSchemaInternalServerError struct {
}

func (o *ValidateSchemaInternalServerError) Error() string {
	return fmt.Sprintf("[POST /schemas/validate][%d] validateSchemaInternalServerError ", 500)
}

func (o *ValidateSchemaInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
