// Code generated by go-swagger; DO NOT EDIT.

package tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spaghettifunk/pinot-go-client/models"
)

// GetTenantMetadataReader is a Reader for the GetTenantMetadata structure.
type GetTenantMetadataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTenantMetadataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTenantMetadataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetTenantMetadataNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTenantMetadataInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTenantMetadataOK creates a GetTenantMetadataOK with default headers values
func NewGetTenantMetadataOK() *GetTenantMetadataOK {
	return &GetTenantMetadataOK{}
}

/*GetTenantMetadataOK handles this case with default header values.

Success
*/
type GetTenantMetadataOK struct {
	Payload *models.TenantMetadata
}

func (o *GetTenantMetadataOK) Error() string {
	return fmt.Sprintf("[GET /tenants/{tenantName}/metadata][%d] getTenantMetadataOK  %+v", 200, o.Payload)
}

func (o *GetTenantMetadataOK) GetPayload() *models.TenantMetadata {
	return o.Payload
}

func (o *GetTenantMetadataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TenantMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTenantMetadataNotFound creates a GetTenantMetadataNotFound with default headers values
func NewGetTenantMetadataNotFound() *GetTenantMetadataNotFound {
	return &GetTenantMetadataNotFound{}
}

/*GetTenantMetadataNotFound handles this case with default header values.

Tenant not found
*/
type GetTenantMetadataNotFound struct {
}

func (o *GetTenantMetadataNotFound) Error() string {
	return fmt.Sprintf("[GET /tenants/{tenantName}/metadata][%d] getTenantMetadataNotFound ", 404)
}

func (o *GetTenantMetadataNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTenantMetadataInternalServerError creates a GetTenantMetadataInternalServerError with default headers values
func NewGetTenantMetadataInternalServerError() *GetTenantMetadataInternalServerError {
	return &GetTenantMetadataInternalServerError{}
}

/*GetTenantMetadataInternalServerError handles this case with default header values.

Server error reading tenant information
*/
type GetTenantMetadataInternalServerError struct {
}

func (o *GetTenantMetadataInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tenants/{tenantName}/metadata][%d] getTenantMetadataInternalServerError ", 500)
}

func (o *GetTenantMetadataInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
