// Code generated by go-swagger; DO NOT EDIT.

package tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetTablesOnTenantReader is a Reader for the GetTablesOnTenant structure.
type GetTablesOnTenantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTablesOnTenantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTablesOnTenantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetTablesOnTenantInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTablesOnTenantOK creates a GetTablesOnTenantOK with default headers values
func NewGetTablesOnTenantOK() *GetTablesOnTenantOK {
	return &GetTablesOnTenantOK{}
}

/*GetTablesOnTenantOK handles this case with default header values.

Success
*/
type GetTablesOnTenantOK struct {
}

func (o *GetTablesOnTenantOK) Error() string {
	return fmt.Sprintf("[GET /tenants/{tenantName}/tables][%d] getTablesOnTenantOK ", 200)
}

func (o *GetTablesOnTenantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTablesOnTenantInternalServerError creates a GetTablesOnTenantInternalServerError with default headers values
func NewGetTablesOnTenantInternalServerError() *GetTablesOnTenantInternalServerError {
	return &GetTablesOnTenantInternalServerError{}
}

/*GetTablesOnTenantInternalServerError handles this case with default header values.

Error reading list
*/
type GetTablesOnTenantInternalServerError struct {
}

func (o *GetTablesOnTenantInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tenants/{tenantName}/tables][%d] getTablesOnTenantInternalServerError ", 500)
}

func (o *GetTablesOnTenantInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
