// Code generated by go-swagger; DO NOT EDIT.

package tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ListInstanceOrToggleTenantStateReader is a Reader for the ListInstanceOrToggleTenantState structure.
type ListInstanceOrToggleTenantStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListInstanceOrToggleTenantStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListInstanceOrToggleTenantStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListInstanceOrToggleTenantStateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListInstanceOrToggleTenantStateOK creates a ListInstanceOrToggleTenantStateOK with default headers values
func NewListInstanceOrToggleTenantStateOK() *ListInstanceOrToggleTenantStateOK {
	return &ListInstanceOrToggleTenantStateOK{}
}

/*ListInstanceOrToggleTenantStateOK handles this case with default header values.

Success
*/
type ListInstanceOrToggleTenantStateOK struct {
}

func (o *ListInstanceOrToggleTenantStateOK) Error() string {
	return fmt.Sprintf("[GET /tenants/{tenantName}][%d] listInstanceOrToggleTenantStateOK ", 200)
}

func (o *ListInstanceOrToggleTenantStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListInstanceOrToggleTenantStateInternalServerError creates a ListInstanceOrToggleTenantStateInternalServerError with default headers values
func NewListInstanceOrToggleTenantStateInternalServerError() *ListInstanceOrToggleTenantStateInternalServerError {
	return &ListInstanceOrToggleTenantStateInternalServerError{}
}

/*ListInstanceOrToggleTenantStateInternalServerError handles this case with default header values.

Error reading tenants list
*/
type ListInstanceOrToggleTenantStateInternalServerError struct {
}

func (o *ListInstanceOrToggleTenantStateInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tenants/{tenantName}][%d] listInstanceOrToggleTenantStateInternalServerError ", 500)
}

func (o *ListInstanceOrToggleTenantStateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
