// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spaghettifunk/pinot-go-client/models"
)

// DeleteTaskQueueReader is a Reader for the DeleteTaskQueue structure.
type DeleteTaskQueueReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTaskQueueReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteTaskQueueOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteTaskQueueOK creates a DeleteTaskQueueOK with default headers values
func NewDeleteTaskQueueOK() *DeleteTaskQueueOK {
	return &DeleteTaskQueueOK{}
}

/*DeleteTaskQueueOK handles this case with default header values.

successful operation
*/
type DeleteTaskQueueOK struct {
	Payload *models.SuccessResponse
}

func (o *DeleteTaskQueueOK) Error() string {
	return fmt.Sprintf("[DELETE /tasks/taskqueue/{taskType}][%d] deleteTaskQueueOK  %+v", 200, o.Payload)
}

func (o *DeleteTaskQueueOK) GetPayload() *models.SuccessResponse {
	return o.Payload
}

func (o *DeleteTaskQueueOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
