// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTaskQueueStateDeprecatedParams creates a new GetTaskQueueStateDeprecatedParams object
// with the default values initialized.
func NewGetTaskQueueStateDeprecatedParams() *GetTaskQueueStateDeprecatedParams {
	var ()
	return &GetTaskQueueStateDeprecatedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTaskQueueStateDeprecatedParamsWithTimeout creates a new GetTaskQueueStateDeprecatedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTaskQueueStateDeprecatedParamsWithTimeout(timeout time.Duration) *GetTaskQueueStateDeprecatedParams {
	var ()
	return &GetTaskQueueStateDeprecatedParams{

		timeout: timeout,
	}
}

// NewGetTaskQueueStateDeprecatedParamsWithContext creates a new GetTaskQueueStateDeprecatedParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTaskQueueStateDeprecatedParamsWithContext(ctx context.Context) *GetTaskQueueStateDeprecatedParams {
	var ()
	return &GetTaskQueueStateDeprecatedParams{

		Context: ctx,
	}
}

// NewGetTaskQueueStateDeprecatedParamsWithHTTPClient creates a new GetTaskQueueStateDeprecatedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTaskQueueStateDeprecatedParamsWithHTTPClient(client *http.Client) *GetTaskQueueStateDeprecatedParams {
	var ()
	return &GetTaskQueueStateDeprecatedParams{
		HTTPClient: client,
	}
}

/*GetTaskQueueStateDeprecatedParams contains all the parameters to send to the API endpoint
for the get task queue state deprecated operation typically these are written to a http.Request
*/
type GetTaskQueueStateDeprecatedParams struct {

	/*TaskType
	  Task type

	*/
	TaskType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get task queue state deprecated params
func (o *GetTaskQueueStateDeprecatedParams) WithTimeout(timeout time.Duration) *GetTaskQueueStateDeprecatedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get task queue state deprecated params
func (o *GetTaskQueueStateDeprecatedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get task queue state deprecated params
func (o *GetTaskQueueStateDeprecatedParams) WithContext(ctx context.Context) *GetTaskQueueStateDeprecatedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get task queue state deprecated params
func (o *GetTaskQueueStateDeprecatedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get task queue state deprecated params
func (o *GetTaskQueueStateDeprecatedParams) WithHTTPClient(client *http.Client) *GetTaskQueueStateDeprecatedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get task queue state deprecated params
func (o *GetTaskQueueStateDeprecatedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskType adds the taskType to the get task queue state deprecated params
func (o *GetTaskQueueStateDeprecatedParams) WithTaskType(taskType string) *GetTaskQueueStateDeprecatedParams {
	o.SetTaskType(taskType)
	return o
}

// SetTaskType adds the taskType to the get task queue state deprecated params
func (o *GetTaskQueueStateDeprecatedParams) SetTaskType(taskType string) {
	o.TaskType = taskType
}

// WriteToRequest writes these params to a swagger request
func (o *GetTaskQueueStateDeprecatedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param taskType
	if err := r.SetPathParam("taskType", o.TaskType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
