// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTaskStateParams creates a new GetTaskStateParams object
// with the default values initialized.
func NewGetTaskStateParams() *GetTaskStateParams {
	var ()
	return &GetTaskStateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTaskStateParamsWithTimeout creates a new GetTaskStateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTaskStateParamsWithTimeout(timeout time.Duration) *GetTaskStateParams {
	var ()
	return &GetTaskStateParams{

		timeout: timeout,
	}
}

// NewGetTaskStateParamsWithContext creates a new GetTaskStateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTaskStateParamsWithContext(ctx context.Context) *GetTaskStateParams {
	var ()
	return &GetTaskStateParams{

		Context: ctx,
	}
}

// NewGetTaskStateParamsWithHTTPClient creates a new GetTaskStateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTaskStateParamsWithHTTPClient(client *http.Client) *GetTaskStateParams {
	var ()
	return &GetTaskStateParams{
		HTTPClient: client,
	}
}

/*GetTaskStateParams contains all the parameters to send to the API endpoint
for the get task state operation typically these are written to a http.Request
*/
type GetTaskStateParams struct {

	/*TaskName
	  Task name

	*/
	TaskName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get task state params
func (o *GetTaskStateParams) WithTimeout(timeout time.Duration) *GetTaskStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get task state params
func (o *GetTaskStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get task state params
func (o *GetTaskStateParams) WithContext(ctx context.Context) *GetTaskStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get task state params
func (o *GetTaskStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get task state params
func (o *GetTaskStateParams) WithHTTPClient(client *http.Client) *GetTaskStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get task state params
func (o *GetTaskStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskName adds the taskName to the get task state params
func (o *GetTaskStateParams) WithTaskName(taskName string) *GetTaskStateParams {
	o.SetTaskName(taskName)
	return o
}

// SetTaskName adds the taskName to the get task state params
func (o *GetTaskStateParams) SetTaskName(taskName string) {
	o.TaskName = taskName
}

// WriteToRequest writes these params to a swagger request
func (o *GetTaskStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param taskName
	if err := r.SetPathParam("taskName", o.TaskName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
