// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spaghettifunk/pinot-go-client/models"
)

// GetTaskConfigsReader is a Reader for the GetTaskConfigs structure.
type GetTaskConfigsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTaskConfigsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTaskConfigsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTaskConfigsOK creates a GetTaskConfigsOK with default headers values
func NewGetTaskConfigsOK() *GetTaskConfigsOK {
	return &GetTaskConfigsOK{}
}

/*GetTaskConfigsOK handles this case with default header values.

successful operation
*/
type GetTaskConfigsOK struct {
	Payload []*models.PinotTaskConfig
}

func (o *GetTaskConfigsOK) Error() string {
	return fmt.Sprintf("[GET /tasks/task/{taskName}/config][%d] getTaskConfigsOK  %+v", 200, o.Payload)
}

func (o *GetTaskConfigsOK) GetPayload() []*models.PinotTaskConfig {
	return o.Payload
}

func (o *GetTaskConfigsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
