// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetTaskQueueStateReader is a Reader for the GetTaskQueueState structure.
type GetTaskQueueStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTaskQueueStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTaskQueueStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTaskQueueStateOK creates a GetTaskQueueStateOK with default headers values
func NewGetTaskQueueStateOK() *GetTaskQueueStateOK {
	return &GetTaskQueueStateOK{}
}

/*GetTaskQueueStateOK handles this case with default header values.

successful operation
*/
type GetTaskQueueStateOK struct {
	Payload string
}

func (o *GetTaskQueueStateOK) Error() string {
	return fmt.Sprintf("[GET /tasks/{taskType}/state][%d] getTaskQueueStateOK  %+v", 200, o.Payload)
}

func (o *GetTaskQueueStateOK) GetPayload() string {
	return o.Payload
}

func (o *GetTaskQueueStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
