// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spaghettifunk/pinot-go-client/models"
)

// GetTaskQueueStateDeprecatedReader is a Reader for the GetTaskQueueStateDeprecated structure.
type GetTaskQueueStateDeprecatedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTaskQueueStateDeprecatedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTaskQueueStateDeprecatedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTaskQueueStateDeprecatedOK creates a GetTaskQueueStateDeprecatedOK with default headers values
func NewGetTaskQueueStateDeprecatedOK() *GetTaskQueueStateDeprecatedOK {
	return &GetTaskQueueStateDeprecatedOK{}
}

/*GetTaskQueueStateDeprecatedOK handles this case with default header values.

successful operation
*/
type GetTaskQueueStateDeprecatedOK struct {
	Payload *models.StringResultResponse
}

func (o *GetTaskQueueStateDeprecatedOK) Error() string {
	return fmt.Sprintf("[GET /tasks/taskqueuestate/{taskType}][%d] getTaskQueueStateDeprecatedOK  %+v", 200, o.Payload)
}

func (o *GetTaskQueueStateDeprecatedOK) GetPayload() *models.StringResultResponse {
	return o.Payload
}

func (o *GetTaskQueueStateDeprecatedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StringResultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
