// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTaskStatesDeprecatedParams creates a new GetTaskStatesDeprecatedParams object
// with the default values initialized.
func NewGetTaskStatesDeprecatedParams() *GetTaskStatesDeprecatedParams {
	var ()
	return &GetTaskStatesDeprecatedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTaskStatesDeprecatedParamsWithTimeout creates a new GetTaskStatesDeprecatedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTaskStatesDeprecatedParamsWithTimeout(timeout time.Duration) *GetTaskStatesDeprecatedParams {
	var ()
	return &GetTaskStatesDeprecatedParams{

		timeout: timeout,
	}
}

// NewGetTaskStatesDeprecatedParamsWithContext creates a new GetTaskStatesDeprecatedParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTaskStatesDeprecatedParamsWithContext(ctx context.Context) *GetTaskStatesDeprecatedParams {
	var ()
	return &GetTaskStatesDeprecatedParams{

		Context: ctx,
	}
}

// NewGetTaskStatesDeprecatedParamsWithHTTPClient creates a new GetTaskStatesDeprecatedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTaskStatesDeprecatedParamsWithHTTPClient(client *http.Client) *GetTaskStatesDeprecatedParams {
	var ()
	return &GetTaskStatesDeprecatedParams{
		HTTPClient: client,
	}
}

/*GetTaskStatesDeprecatedParams contains all the parameters to send to the API endpoint
for the get task states deprecated operation typically these are written to a http.Request
*/
type GetTaskStatesDeprecatedParams struct {

	/*TaskType
	  Task type

	*/
	TaskType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get task states deprecated params
func (o *GetTaskStatesDeprecatedParams) WithTimeout(timeout time.Duration) *GetTaskStatesDeprecatedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get task states deprecated params
func (o *GetTaskStatesDeprecatedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get task states deprecated params
func (o *GetTaskStatesDeprecatedParams) WithContext(ctx context.Context) *GetTaskStatesDeprecatedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get task states deprecated params
func (o *GetTaskStatesDeprecatedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get task states deprecated params
func (o *GetTaskStatesDeprecatedParams) WithHTTPClient(client *http.Client) *GetTaskStatesDeprecatedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get task states deprecated params
func (o *GetTaskStatesDeprecatedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskType adds the taskType to the get task states deprecated params
func (o *GetTaskStatesDeprecatedParams) WithTaskType(taskType string) *GetTaskStatesDeprecatedParams {
	o.SetTaskType(taskType)
	return o
}

// SetTaskType adds the taskType to the get task states deprecated params
func (o *GetTaskStatesDeprecatedParams) SetTaskType(taskType string) {
	o.TaskType = taskType
}

// WriteToRequest writes these params to a swagger request
func (o *GetTaskStatesDeprecatedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param taskType
	if err := r.SetPathParam("taskType", o.TaskType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
