// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetTaskStatesDeprecatedReader is a Reader for the GetTaskStatesDeprecated structure.
type GetTaskStatesDeprecatedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTaskStatesDeprecatedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTaskStatesDeprecatedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTaskStatesDeprecatedOK creates a GetTaskStatesDeprecatedOK with default headers values
func NewGetTaskStatesDeprecatedOK() *GetTaskStatesDeprecatedOK {
	return &GetTaskStatesDeprecatedOK{}
}

/*GetTaskStatesDeprecatedOK handles this case with default header values.

successful operation
*/
type GetTaskStatesDeprecatedOK struct {
	Payload map[string]string
}

func (o *GetTaskStatesDeprecatedOK) Error() string {
	return fmt.Sprintf("[GET /tasks/taskstates/{taskType}][%d] getTaskStatesDeprecatedOK  %+v", 200, o.Payload)
}

func (o *GetTaskStatesDeprecatedOK) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetTaskStatesDeprecatedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
