// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTaskConfigsParams creates a new GetTaskConfigsParams object
// with the default values initialized.
func NewGetTaskConfigsParams() *GetTaskConfigsParams {
	var ()
	return &GetTaskConfigsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTaskConfigsParamsWithTimeout creates a new GetTaskConfigsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTaskConfigsParamsWithTimeout(timeout time.Duration) *GetTaskConfigsParams {
	var ()
	return &GetTaskConfigsParams{

		timeout: timeout,
	}
}

// NewGetTaskConfigsParamsWithContext creates a new GetTaskConfigsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTaskConfigsParamsWithContext(ctx context.Context) *GetTaskConfigsParams {
	var ()
	return &GetTaskConfigsParams{

		Context: ctx,
	}
}

// NewGetTaskConfigsParamsWithHTTPClient creates a new GetTaskConfigsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTaskConfigsParamsWithHTTPClient(client *http.Client) *GetTaskConfigsParams {
	var ()
	return &GetTaskConfigsParams{
		HTTPClient: client,
	}
}

/*GetTaskConfigsParams contains all the parameters to send to the API endpoint
for the get task configs operation typically these are written to a http.Request
*/
type GetTaskConfigsParams struct {

	/*TaskName
	  Task name

	*/
	TaskName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get task configs params
func (o *GetTaskConfigsParams) WithTimeout(timeout time.Duration) *GetTaskConfigsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get task configs params
func (o *GetTaskConfigsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get task configs params
func (o *GetTaskConfigsParams) WithContext(ctx context.Context) *GetTaskConfigsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get task configs params
func (o *GetTaskConfigsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get task configs params
func (o *GetTaskConfigsParams) WithHTTPClient(client *http.Client) *GetTaskConfigsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get task configs params
func (o *GetTaskConfigsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskName adds the taskName to the get task configs params
func (o *GetTaskConfigsParams) WithTaskName(taskName string) *GetTaskConfigsParams {
	o.SetTaskName(taskName)
	return o
}

// SetTaskName adds the taskName to the get task configs params
func (o *GetTaskConfigsParams) SetTaskName(taskName string) {
	o.TaskName = taskName
}

// WriteToRequest writes these params to a swagger request
func (o *GetTaskConfigsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param taskName
	if err := r.SetPathParam("taskName", o.TaskName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
