// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ListTaskTypesReader is a Reader for the ListTaskTypes structure.
type ListTaskTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListTaskTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListTaskTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListTaskTypesOK creates a ListTaskTypesOK with default headers values
func NewListTaskTypesOK() *ListTaskTypesOK {
	return &ListTaskTypesOK{}
}

/*ListTaskTypesOK handles this case with default header values.

successful operation
*/
type ListTaskTypesOK struct {
	Payload []string
}

func (o *ListTaskTypesOK) Error() string {
	return fmt.Sprintf("[GET /tasks/tasktypes][%d] listTaskTypesOK  %+v", 200, o.Payload)
}

func (o *ListTaskTypesOK) GetPayload() []string {
	return o.Payload
}

func (o *ListTaskTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
