// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewResumeTasksParams creates a new ResumeTasksParams object
// with the default values initialized.
func NewResumeTasksParams() *ResumeTasksParams {
	var ()
	return &ResumeTasksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewResumeTasksParamsWithTimeout creates a new ResumeTasksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewResumeTasksParamsWithTimeout(timeout time.Duration) *ResumeTasksParams {
	var ()
	return &ResumeTasksParams{

		timeout: timeout,
	}
}

// NewResumeTasksParamsWithContext creates a new ResumeTasksParams object
// with the default values initialized, and the ability to set a context for a request
func NewResumeTasksParamsWithContext(ctx context.Context) *ResumeTasksParams {
	var ()
	return &ResumeTasksParams{

		Context: ctx,
	}
}

// NewResumeTasksParamsWithHTTPClient creates a new ResumeTasksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewResumeTasksParamsWithHTTPClient(client *http.Client) *ResumeTasksParams {
	var ()
	return &ResumeTasksParams{
		HTTPClient: client,
	}
}

/*ResumeTasksParams contains all the parameters to send to the API endpoint
for the resume tasks operation typically these are written to a http.Request
*/
type ResumeTasksParams struct {

	/*TaskType
	  Task type

	*/
	TaskType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the resume tasks params
func (o *ResumeTasksParams) WithTimeout(timeout time.Duration) *ResumeTasksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resume tasks params
func (o *ResumeTasksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resume tasks params
func (o *ResumeTasksParams) WithContext(ctx context.Context) *ResumeTasksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resume tasks params
func (o *ResumeTasksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resume tasks params
func (o *ResumeTasksParams) WithHTTPClient(client *http.Client) *ResumeTasksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resume tasks params
func (o *ResumeTasksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskType adds the taskType to the resume tasks params
func (o *ResumeTasksParams) WithTaskType(taskType string) *ResumeTasksParams {
	o.SetTaskType(taskType)
	return o
}

// SetTaskType adds the taskType to the resume tasks params
func (o *ResumeTasksParams) SetTaskType(taskType string) {
	o.TaskType = taskType
}

// WriteToRequest writes these params to a swagger request
func (o *ResumeTasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param taskType
	if err := r.SetPathParam("taskType", o.TaskType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
