// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ScheduleTasksReader is a Reader for the ScheduleTasks structure.
type ScheduleTasksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ScheduleTasksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewScheduleTasksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewScheduleTasksOK creates a ScheduleTasksOK with default headers values
func NewScheduleTasksOK() *ScheduleTasksOK {
	return &ScheduleTasksOK{}
}

/*ScheduleTasksOK handles this case with default header values.

successful operation
*/
type ScheduleTasksOK struct {
	Payload map[string]string
}

func (o *ScheduleTasksOK) Error() string {
	return fmt.Sprintf("[POST /tasks/schedule][%d] scheduleTasksOK  %+v", 200, o.Payload)
}

func (o *ScheduleTasksOK) GetPayload() map[string]string {
	return o.Payload
}

func (o *ScheduleTasksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
