// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewToggleTaskQueueStateParams creates a new ToggleTaskQueueStateParams object
// with the default values initialized.
func NewToggleTaskQueueStateParams() *ToggleTaskQueueStateParams {
	var ()
	return &ToggleTaskQueueStateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewToggleTaskQueueStateParamsWithTimeout creates a new ToggleTaskQueueStateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewToggleTaskQueueStateParamsWithTimeout(timeout time.Duration) *ToggleTaskQueueStateParams {
	var ()
	return &ToggleTaskQueueStateParams{

		timeout: timeout,
	}
}

// NewToggleTaskQueueStateParamsWithContext creates a new ToggleTaskQueueStateParams object
// with the default values initialized, and the ability to set a context for a request
func NewToggleTaskQueueStateParamsWithContext(ctx context.Context) *ToggleTaskQueueStateParams {
	var ()
	return &ToggleTaskQueueStateParams{

		Context: ctx,
	}
}

// NewToggleTaskQueueStateParamsWithHTTPClient creates a new ToggleTaskQueueStateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewToggleTaskQueueStateParamsWithHTTPClient(client *http.Client) *ToggleTaskQueueStateParams {
	var ()
	return &ToggleTaskQueueStateParams{
		HTTPClient: client,
	}
}

/*ToggleTaskQueueStateParams contains all the parameters to send to the API endpoint
for the toggle task queue state operation typically these are written to a http.Request
*/
type ToggleTaskQueueStateParams struct {

	/*State
	  state

	*/
	State string
	/*TaskType
	  Task type

	*/
	TaskType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the toggle task queue state params
func (o *ToggleTaskQueueStateParams) WithTimeout(timeout time.Duration) *ToggleTaskQueueStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the toggle task queue state params
func (o *ToggleTaskQueueStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the toggle task queue state params
func (o *ToggleTaskQueueStateParams) WithContext(ctx context.Context) *ToggleTaskQueueStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the toggle task queue state params
func (o *ToggleTaskQueueStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the toggle task queue state params
func (o *ToggleTaskQueueStateParams) WithHTTPClient(client *http.Client) *ToggleTaskQueueStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the toggle task queue state params
func (o *ToggleTaskQueueStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithState adds the state to the toggle task queue state params
func (o *ToggleTaskQueueStateParams) WithState(state string) *ToggleTaskQueueStateParams {
	o.SetState(state)
	return o
}

// SetState adds the state to the toggle task queue state params
func (o *ToggleTaskQueueStateParams) SetState(state string) {
	o.State = state
}

// WithTaskType adds the taskType to the toggle task queue state params
func (o *ToggleTaskQueueStateParams) WithTaskType(taskType string) *ToggleTaskQueueStateParams {
	o.SetTaskType(taskType)
	return o
}

// SetTaskType adds the taskType to the toggle task queue state params
func (o *ToggleTaskQueueStateParams) SetTaskType(taskType string) {
	o.TaskType = taskType
}

// WriteToRequest writes these params to a swagger request
func (o *ToggleTaskQueueStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param state
	qrState := o.State
	qState := qrState
	if qState != "" {
		if err := r.SetQueryParam("state", qState); err != nil {
			return err
		}
	}

	// path param taskType
	if err := r.SetPathParam("taskType", o.TaskType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
