// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCheckTableConfigParams creates a new CheckTableConfigParams object
// with the default values initialized.
func NewCheckTableConfigParams() *CheckTableConfigParams {
	var ()
	return &CheckTableConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCheckTableConfigParamsWithTimeout creates a new CheckTableConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCheckTableConfigParamsWithTimeout(timeout time.Duration) *CheckTableConfigParams {
	var ()
	return &CheckTableConfigParams{

		timeout: timeout,
	}
}

// NewCheckTableConfigParamsWithContext creates a new CheckTableConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewCheckTableConfigParamsWithContext(ctx context.Context) *CheckTableConfigParams {
	var ()
	return &CheckTableConfigParams{

		Context: ctx,
	}
}

// NewCheckTableConfigParamsWithHTTPClient creates a new CheckTableConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCheckTableConfigParamsWithHTTPClient(client *http.Client) *CheckTableConfigParams {
	var ()
	return &CheckTableConfigParams{
		HTTPClient: client,
	}
}

/*CheckTableConfigParams contains all the parameters to send to the API endpoint
for the check table config operation typically these are written to a http.Request
*/
type CheckTableConfigParams struct {

	/*Body*/
	Body string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the check table config params
func (o *CheckTableConfigParams) WithTimeout(timeout time.Duration) *CheckTableConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check table config params
func (o *CheckTableConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check table config params
func (o *CheckTableConfigParams) WithContext(ctx context.Context) *CheckTableConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check table config params
func (o *CheckTableConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check table config params
func (o *CheckTableConfigParams) WithHTTPClient(client *http.Client) *CheckTableConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check table config params
func (o *CheckTableConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the check table config params
func (o *CheckTableConfigParams) WithBody(body string) *CheckTableConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the check table config params
func (o *CheckTableConfigParams) SetBody(body string) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CheckTableConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
