// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetTableInstancesReader is a Reader for the GetTableInstances structure.
type GetTableInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTableInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTableInstancesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetTableInstancesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTableInstancesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTableInstancesOK creates a GetTableInstancesOK with default headers values
func NewGetTableInstancesOK() *GetTableInstancesOK {
	return &GetTableInstancesOK{}
}

/*GetTableInstancesOK handles this case with default header values.

Success
*/
type GetTableInstancesOK struct {
}

func (o *GetTableInstancesOK) Error() string {
	return fmt.Sprintf("[GET /tables/{tableName}/instances][%d] getTableInstancesOK ", 200)
}

func (o *GetTableInstancesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTableInstancesNotFound creates a GetTableInstancesNotFound with default headers values
func NewGetTableInstancesNotFound() *GetTableInstancesNotFound {
	return &GetTableInstancesNotFound{}
}

/*GetTableInstancesNotFound handles this case with default header values.

Table not found
*/
type GetTableInstancesNotFound struct {
}

func (o *GetTableInstancesNotFound) Error() string {
	return fmt.Sprintf("[GET /tables/{tableName}/instances][%d] getTableInstancesNotFound ", 404)
}

func (o *GetTableInstancesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTableInstancesInternalServerError creates a GetTableInstancesInternalServerError with default headers values
func NewGetTableInstancesInternalServerError() *GetTableInstancesInternalServerError {
	return &GetTableInstancesInternalServerError{}
}

/*GetTableInstancesInternalServerError handles this case with default header values.

Internal server error
*/
type GetTableInstancesInternalServerError struct {
}

func (o *GetTableInstancesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tables/{tableName}/instances][%d] getTableInstancesInternalServerError ", 500)
}

func (o *GetTableInstancesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
