// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spaghettifunk/pinot-go-client/models"
)

// GetInstancePartitionsReader is a Reader for the GetInstancePartitions structure.
type GetInstancePartitionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInstancePartitionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInstancePartitionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetInstancePartitionsOK creates a GetInstancePartitionsOK with default headers values
func NewGetInstancePartitionsOK() *GetInstancePartitionsOK {
	return &GetInstancePartitionsOK{}
}

/*GetInstancePartitionsOK handles this case with default header values.

successful operation
*/
type GetInstancePartitionsOK struct {
	Payload map[string]models.InstancePartitions
}

func (o *GetInstancePartitionsOK) Error() string {
	return fmt.Sprintf("[GET /tables/{tableName}/instancePartitions][%d] getInstancePartitionsOK  %+v", 200, o.Payload)
}

func (o *GetInstancePartitionsOK) GetPayload() map[string]models.InstancePartitions {
	return o.Payload
}

func (o *GetInstancePartitionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
