// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetIdealStateParams creates a new GetIdealStateParams object
// with the default values initialized.
func NewGetIdealStateParams() *GetIdealStateParams {
	var ()
	return &GetIdealStateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIdealStateParamsWithTimeout creates a new GetIdealStateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIdealStateParamsWithTimeout(timeout time.Duration) *GetIdealStateParams {
	var ()
	return &GetIdealStateParams{

		timeout: timeout,
	}
}

// NewGetIdealStateParamsWithContext creates a new GetIdealStateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIdealStateParamsWithContext(ctx context.Context) *GetIdealStateParams {
	var ()
	return &GetIdealStateParams{

		Context: ctx,
	}
}

// NewGetIdealStateParamsWithHTTPClient creates a new GetIdealStateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIdealStateParamsWithHTTPClient(client *http.Client) *GetIdealStateParams {
	var ()
	return &GetIdealStateParams{
		HTTPClient: client,
	}
}

/*GetIdealStateParams contains all the parameters to send to the API endpoint
for the get ideal state operation typically these are written to a http.Request
*/
type GetIdealStateParams struct {

	/*TableName
	  Name of the table

	*/
	TableName string
	/*TableType
	  realtime|offline

	*/
	TableType *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get ideal state params
func (o *GetIdealStateParams) WithTimeout(timeout time.Duration) *GetIdealStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ideal state params
func (o *GetIdealStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ideal state params
func (o *GetIdealStateParams) WithContext(ctx context.Context) *GetIdealStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ideal state params
func (o *GetIdealStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ideal state params
func (o *GetIdealStateParams) WithHTTPClient(client *http.Client) *GetIdealStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ideal state params
func (o *GetIdealStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTableName adds the tableName to the get ideal state params
func (o *GetIdealStateParams) WithTableName(tableName string) *GetIdealStateParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the get ideal state params
func (o *GetIdealStateParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WithTableType adds the tableType to the get ideal state params
func (o *GetIdealStateParams) WithTableType(tableType *string) *GetIdealStateParams {
	o.SetTableType(tableType)
	return o
}

// SetTableType adds the tableType to the get ideal state params
func (o *GetIdealStateParams) SetTableType(tableType *string) {
	o.TableType = tableType
}

// WriteToRequest writes these params to a swagger request
func (o *GetIdealStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if o.TableType != nil {

		// query param tableType
		var qrTableType string
		if o.TableType != nil {
			qrTableType = *o.TableType
		}
		qTableType := qrTableType
		if qTableType != "" {
			if err := r.SetQueryParam("tableType", qTableType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
