// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spaghettifunk/pinot-go-client/models"
)

// GetExternalViewReader is a Reader for the GetExternalView structure.
type GetExternalViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetExternalViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetExternalViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetExternalViewOK creates a GetExternalViewOK with default headers values
func NewGetExternalViewOK() *GetExternalViewOK {
	return &GetExternalViewOK{}
}

/*GetExternalViewOK handles this case with default header values.

successful operation
*/
type GetExternalViewOK struct {
	Payload *models.TableView
}

func (o *GetExternalViewOK) Error() string {
	return fmt.Sprintf("[GET /tables/{tableName}/externalview][%d] getExternalViewOK  %+v", 200, o.Payload)
}

func (o *GetExternalViewOK) GetPayload() *models.TableView {
	return o.Payload
}

func (o *GetExternalViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TableView)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
