// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// IngestFromFileReader is a Reader for the IngestFromFile structure.
type IngestFromFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IngestFromFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewIngestFromFileDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewIngestFromFileDefault creates a IngestFromFileDefault with default headers values
func NewIngestFromFileDefault(code int) *IngestFromFileDefault {
	return &IngestFromFileDefault{
		_statusCode: code,
	}
}

/*IngestFromFileDefault handles this case with default header values.

successful operation
*/
type IngestFromFileDefault struct {
	_statusCode int
}

// Code gets the status code for the ingest from file default response
func (o *IngestFromFileDefault) Code() int {
	return o._statusCode
}

func (o *IngestFromFileDefault) Error() string {
	return fmt.Sprintf("[POST /ingestFromFile][%d] ingestFromFile default ", o._statusCode)
}

func (o *IngestFromFileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
