// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spaghettifunk/pinot-go-client/models"
)

// RebalanceReader is a Reader for the Rebalance structure.
type RebalanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RebalanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRebalanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRebalanceOK creates a RebalanceOK with default headers values
func NewRebalanceOK() *RebalanceOK {
	return &RebalanceOK{}
}

/*RebalanceOK handles this case with default header values.

successful operation
*/
type RebalanceOK struct {
	Payload *models.RebalanceResult
}

func (o *RebalanceOK) Error() string {
	return fmt.Sprintf("[POST /tables/{tableName}/rebalance][%d] rebalanceOK  %+v", 200, o.Payload)
}

func (o *RebalanceOK) GetPayload() *models.RebalanceResult {
	return o.Payload
}

func (o *RebalanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RebalanceResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
