// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateTableMetadataParams creates a new UpdateTableMetadataParams object
// with the default values initialized.
func NewUpdateTableMetadataParams() *UpdateTableMetadataParams {
	var ()
	return &UpdateTableMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateTableMetadataParamsWithTimeout creates a new UpdateTableMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateTableMetadataParamsWithTimeout(timeout time.Duration) *UpdateTableMetadataParams {
	var ()
	return &UpdateTableMetadataParams{

		timeout: timeout,
	}
}

// NewUpdateTableMetadataParamsWithContext creates a new UpdateTableMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateTableMetadataParamsWithContext(ctx context.Context) *UpdateTableMetadataParams {
	var ()
	return &UpdateTableMetadataParams{

		Context: ctx,
	}
}

// NewUpdateTableMetadataParamsWithHTTPClient creates a new UpdateTableMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateTableMetadataParamsWithHTTPClient(client *http.Client) *UpdateTableMetadataParams {
	var ()
	return &UpdateTableMetadataParams{
		HTTPClient: client,
	}
}

/*UpdateTableMetadataParams contains all the parameters to send to the API endpoint
for the update table metadata operation typically these are written to a http.Request
*/
type UpdateTableMetadataParams struct {

	/*Body*/
	Body string
	/*TableName*/
	TableName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update table metadata params
func (o *UpdateTableMetadataParams) WithTimeout(timeout time.Duration) *UpdateTableMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update table metadata params
func (o *UpdateTableMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update table metadata params
func (o *UpdateTableMetadataParams) WithContext(ctx context.Context) *UpdateTableMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update table metadata params
func (o *UpdateTableMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update table metadata params
func (o *UpdateTableMetadataParams) WithHTTPClient(client *http.Client) *UpdateTableMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update table metadata params
func (o *UpdateTableMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update table metadata params
func (o *UpdateTableMetadataParams) WithBody(body string) *UpdateTableMetadataParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update table metadata params
func (o *UpdateTableMetadataParams) SetBody(body string) {
	o.Body = body
}

// WithTableName adds the tableName to the update table metadata params
func (o *UpdateTableMetadataParams) WithTableName(tableName string) *UpdateTableMetadataParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the update table metadata params
func (o *UpdateTableMetadataParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateTableMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
