// Code generated by go-swagger; DO NOT EDIT.

package broker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTablesToBrokersMappingV2Params creates a new GetTablesToBrokersMappingV2Params object
// with the default values initialized.
func NewGetTablesToBrokersMappingV2Params() *GetTablesToBrokersMappingV2Params {
	var ()
	return &GetTablesToBrokersMappingV2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTablesToBrokersMappingV2ParamsWithTimeout creates a new GetTablesToBrokersMappingV2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTablesToBrokersMappingV2ParamsWithTimeout(timeout time.Duration) *GetTablesToBrokersMappingV2Params {
	var ()
	return &GetTablesToBrokersMappingV2Params{

		timeout: timeout,
	}
}

// NewGetTablesToBrokersMappingV2ParamsWithContext creates a new GetTablesToBrokersMappingV2Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetTablesToBrokersMappingV2ParamsWithContext(ctx context.Context) *GetTablesToBrokersMappingV2Params {
	var ()
	return &GetTablesToBrokersMappingV2Params{

		Context: ctx,
	}
}

// NewGetTablesToBrokersMappingV2ParamsWithHTTPClient creates a new GetTablesToBrokersMappingV2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTablesToBrokersMappingV2ParamsWithHTTPClient(client *http.Client) *GetTablesToBrokersMappingV2Params {
	var ()
	return &GetTablesToBrokersMappingV2Params{
		HTTPClient: client,
	}
}

/*GetTablesToBrokersMappingV2Params contains all the parameters to send to the API endpoint
for the get tables to brokers mapping v2 operation typically these are written to a http.Request
*/
type GetTablesToBrokersMappingV2Params struct {

	/*State
	  ONLINE|OFFLINE

	*/
	State *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get tables to brokers mapping v2 params
func (o *GetTablesToBrokersMappingV2Params) WithTimeout(timeout time.Duration) *GetTablesToBrokersMappingV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tables to brokers mapping v2 params
func (o *GetTablesToBrokersMappingV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tables to brokers mapping v2 params
func (o *GetTablesToBrokersMappingV2Params) WithContext(ctx context.Context) *GetTablesToBrokersMappingV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tables to brokers mapping v2 params
func (o *GetTablesToBrokersMappingV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tables to brokers mapping v2 params
func (o *GetTablesToBrokersMappingV2Params) WithHTTPClient(client *http.Client) *GetTablesToBrokersMappingV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tables to brokers mapping v2 params
func (o *GetTablesToBrokersMappingV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithState adds the state to the get tables to brokers mapping v2 params
func (o *GetTablesToBrokersMappingV2Params) WithState(state *string) *GetTablesToBrokersMappingV2Params {
	o.SetState(state)
	return o
}

// SetState adds the state to the get tables to brokers mapping v2 params
func (o *GetTablesToBrokersMappingV2Params) SetState(state *string) {
	o.State = state
}

// WriteToRequest writes these params to a swagger request
func (o *GetTablesToBrokersMappingV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.State != nil {

		// query param state
		var qrState string
		if o.State != nil {
			qrState = *o.State
		}
		qState := qrState
		if qState != "" {
			if err := r.SetQueryParam("state", qState); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
