// Code generated by go-swagger; DO NOT EDIT.

package broker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spaghettifunk/pinot-go-client/models"
)

// GetBrokersForTableV2Reader is a Reader for the GetBrokersForTableV2 structure.
type GetBrokersForTableV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBrokersForTableV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBrokersForTableV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBrokersForTableV2OK creates a GetBrokersForTableV2OK with default headers values
func NewGetBrokersForTableV2OK() *GetBrokersForTableV2OK {
	return &GetBrokersForTableV2OK{}
}

/*GetBrokersForTableV2OK handles this case with default header values.

successful operation
*/
type GetBrokersForTableV2OK struct {
	Payload []*models.InstanceInfo
}

func (o *GetBrokersForTableV2OK) Error() string {
	return fmt.Sprintf("[GET /v2/brokers/tables/{tableName}][%d] getBrokersForTableV2OK  %+v", 200, o.Payload)
}

func (o *GetBrokersForTableV2OK) GetPayload() []*models.InstanceInfo {
	return o.Payload
}

func (o *GetBrokersForTableV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
