// Code generated by go-swagger; DO NOT EDIT.

package broker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBrokersForTenantV2Params creates a new GetBrokersForTenantV2Params object
// with the default values initialized.
func NewGetBrokersForTenantV2Params() *GetBrokersForTenantV2Params {
	var ()
	return &GetBrokersForTenantV2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBrokersForTenantV2ParamsWithTimeout creates a new GetBrokersForTenantV2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBrokersForTenantV2ParamsWithTimeout(timeout time.Duration) *GetBrokersForTenantV2Params {
	var ()
	return &GetBrokersForTenantV2Params{

		timeout: timeout,
	}
}

// NewGetBrokersForTenantV2ParamsWithContext creates a new GetBrokersForTenantV2Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetBrokersForTenantV2ParamsWithContext(ctx context.Context) *GetBrokersForTenantV2Params {
	var ()
	return &GetBrokersForTenantV2Params{

		Context: ctx,
	}
}

// NewGetBrokersForTenantV2ParamsWithHTTPClient creates a new GetBrokersForTenantV2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBrokersForTenantV2ParamsWithHTTPClient(client *http.Client) *GetBrokersForTenantV2Params {
	var ()
	return &GetBrokersForTenantV2Params{
		HTTPClient: client,
	}
}

/*GetBrokersForTenantV2Params contains all the parameters to send to the API endpoint
for the get brokers for tenant v2 operation typically these are written to a http.Request
*/
type GetBrokersForTenantV2Params struct {

	/*State
	  ONLINE|OFFLINE

	*/
	State *string
	/*TenantName
	  Name of the tenant

	*/
	TenantName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get brokers for tenant v2 params
func (o *GetBrokersForTenantV2Params) WithTimeout(timeout time.Duration) *GetBrokersForTenantV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get brokers for tenant v2 params
func (o *GetBrokersForTenantV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get brokers for tenant v2 params
func (o *GetBrokersForTenantV2Params) WithContext(ctx context.Context) *GetBrokersForTenantV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get brokers for tenant v2 params
func (o *GetBrokersForTenantV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get brokers for tenant v2 params
func (o *GetBrokersForTenantV2Params) WithHTTPClient(client *http.Client) *GetBrokersForTenantV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get brokers for tenant v2 params
func (o *GetBrokersForTenantV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithState adds the state to the get brokers for tenant v2 params
func (o *GetBrokersForTenantV2Params) WithState(state *string) *GetBrokersForTenantV2Params {
	o.SetState(state)
	return o
}

// SetState adds the state to the get brokers for tenant v2 params
func (o *GetBrokersForTenantV2Params) SetState(state *string) {
	o.State = state
}

// WithTenantName adds the tenantName to the get brokers for tenant v2 params
func (o *GetBrokersForTenantV2Params) WithTenantName(tenantName string) *GetBrokersForTenantV2Params {
	o.SetTenantName(tenantName)
	return o
}

// SetTenantName adds the tenantName to the get brokers for tenant v2 params
func (o *GetBrokersForTenantV2Params) SetTenantName(tenantName string) {
	o.TenantName = tenantName
}

// WriteToRequest writes these params to a swagger request
func (o *GetBrokersForTenantV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.State != nil {

		// query param state
		var qrState string
		if o.State != nil {
			qrState = *o.State
		}
		qState := qrState
		if qState != "" {
			if err := r.SetQueryParam("state", qState); err != nil {
				return err
			}
		}

	}

	// path param tenantName
	if err := r.SetPathParam("tenantName", o.TenantName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
