// Code generated by go-swagger; DO NOT EDIT.

package broker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spaghettifunk/pinot-go-client/models"
)

// GetTenantsToBrokersMappingV2Reader is a Reader for the GetTenantsToBrokersMappingV2 structure.
type GetTenantsToBrokersMappingV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTenantsToBrokersMappingV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTenantsToBrokersMappingV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTenantsToBrokersMappingV2OK creates a GetTenantsToBrokersMappingV2OK with default headers values
func NewGetTenantsToBrokersMappingV2OK() *GetTenantsToBrokersMappingV2OK {
	return &GetTenantsToBrokersMappingV2OK{}
}

/*GetTenantsToBrokersMappingV2OK handles this case with default header values.

successful operation
*/
type GetTenantsToBrokersMappingV2OK struct {
	Payload map[string][]models.InstanceInfo
}

func (o *GetTenantsToBrokersMappingV2OK) Error() string {
	return fmt.Sprintf("[GET /v2/brokers/tenants][%d] getTenantsToBrokersMappingV2OK  %+v", 200, o.Payload)
}

func (o *GetTenantsToBrokersMappingV2OK) GetPayload() map[string][]models.InstanceInfo {
	return o.Payload
}

func (o *GetTenantsToBrokersMappingV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
