// Code generated by go-swagger; DO NOT EDIT.

package broker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ListBrokersMappingReader is a Reader for the ListBrokersMapping structure.
type ListBrokersMappingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListBrokersMappingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListBrokersMappingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListBrokersMappingOK creates a ListBrokersMappingOK with default headers values
func NewListBrokersMappingOK() *ListBrokersMappingOK {
	return &ListBrokersMappingOK{}
}

/*ListBrokersMappingOK handles this case with default header values.

successful operation
*/
type ListBrokersMappingOK struct {
	Payload map[string]map[string][]string
}

func (o *ListBrokersMappingOK) Error() string {
	return fmt.Sprintf("[GET /brokers][%d] listBrokersMappingOK  %+v", 200, o.Payload)
}

func (o *ListBrokersMappingOK) GetPayload() map[string]map[string][]string {
	return o.Payload
}

func (o *ListBrokersMappingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
