// Code generated by go-swagger; DO NOT EDIT.

package version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetVersionNumberReader is a Reader for the GetVersionNumber structure.
type GetVersionNumberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVersionNumberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVersionNumberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetVersionNumberOK creates a GetVersionNumberOK with default headers values
func NewGetVersionNumberOK() *GetVersionNumberOK {
	return &GetVersionNumberOK{}
}

/*GetVersionNumberOK handles this case with default header values.

Success
*/
type GetVersionNumberOK struct {
}

func (o *GetVersionNumberOK) Error() string {
	return fmt.Sprintf("[GET /version][%d] getVersionNumberOK ", 200)
}

func (o *GetVersionNumberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
