// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCheckHealthParams creates a new CheckHealthParams object
// with the default values initialized.
func NewCheckHealthParams() *CheckHealthParams {

	return &CheckHealthParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCheckHealthParamsWithTimeout creates a new CheckHealthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCheckHealthParamsWithTimeout(timeout time.Duration) *CheckHealthParams {

	return &CheckHealthParams{

		timeout: timeout,
	}
}

// NewCheckHealthParamsWithContext creates a new CheckHealthParams object
// with the default values initialized, and the ability to set a context for a request
func NewCheckHealthParamsWithContext(ctx context.Context) *CheckHealthParams {

	return &CheckHealthParams{

		Context: ctx,
	}
}

// NewCheckHealthParamsWithHTTPClient creates a new CheckHealthParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCheckHealthParamsWithHTTPClient(client *http.Client) *CheckHealthParams {

	return &CheckHealthParams{
		HTTPClient: client,
	}
}

/*CheckHealthParams contains all the parameters to send to the API endpoint
for the check health operation typically these are written to a http.Request
*/
type CheckHealthParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the check health params
func (o *CheckHealthParams) WithTimeout(timeout time.Duration) *CheckHealthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check health params
func (o *CheckHealthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check health params
func (o *CheckHealthParams) WithContext(ctx context.Context) *CheckHealthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check health params
func (o *CheckHealthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check health params
func (o *CheckHealthParams) WithHTTPClient(client *http.Client) *CheckHealthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check health params
func (o *CheckHealthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CheckHealthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
