// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new health API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for health API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	CheckHealth(params *CheckHealthParams) (*CheckHealthOK, error)

	CheckHealthLegacy(params *CheckHealthLegacyParams) (*CheckHealthLegacyOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CheckHealth checks controller health
*/
func (a *Client) CheckHealth(params *CheckHealthParams) (*CheckHealthOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCheckHealthParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "checkHealth",
		Method:             "GET",
		PathPattern:        "/health",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CheckHealthReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CheckHealthOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for checkHealth: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  CheckHealthLegacy checks controller health
*/
func (a *Client) CheckHealthLegacy(params *CheckHealthLegacyParams) (*CheckHealthLegacyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCheckHealthLegacyParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "checkHealthLegacy",
		Method:             "GET",
		PathPattern:        "/pinot-controller/admin",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CheckHealthLegacyReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CheckHealthLegacyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for checkHealthLegacy: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
