// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteSegmentsParams creates a new DeleteSegmentsParams object
// with the default values initialized.
func NewDeleteSegmentsParams() *DeleteSegmentsParams {
	var ()
	return &DeleteSegmentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSegmentsParamsWithTimeout creates a new DeleteSegmentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSegmentsParamsWithTimeout(timeout time.Duration) *DeleteSegmentsParams {
	var ()
	return &DeleteSegmentsParams{

		timeout: timeout,
	}
}

// NewDeleteSegmentsParamsWithContext creates a new DeleteSegmentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSegmentsParamsWithContext(ctx context.Context) *DeleteSegmentsParams {
	var ()
	return &DeleteSegmentsParams{

		Context: ctx,
	}
}

// NewDeleteSegmentsParamsWithHTTPClient creates a new DeleteSegmentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSegmentsParamsWithHTTPClient(client *http.Client) *DeleteSegmentsParams {
	var ()
	return &DeleteSegmentsParams{
		HTTPClient: client,
	}
}

/*DeleteSegmentsParams contains all the parameters to send to the API endpoint
for the delete segments operation typically these are written to a http.Request
*/
type DeleteSegmentsParams struct {

	/*Body*/
	Body []string
	/*TableName
	  Name of the table

	*/
	TableName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete segments params
func (o *DeleteSegmentsParams) WithTimeout(timeout time.Duration) *DeleteSegmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete segments params
func (o *DeleteSegmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete segments params
func (o *DeleteSegmentsParams) WithContext(ctx context.Context) *DeleteSegmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete segments params
func (o *DeleteSegmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete segments params
func (o *DeleteSegmentsParams) WithHTTPClient(client *http.Client) *DeleteSegmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete segments params
func (o *DeleteSegmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete segments params
func (o *DeleteSegmentsParams) WithBody(body []string) *DeleteSegmentsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete segments params
func (o *DeleteSegmentsParams) SetBody(body []string) {
	o.Body = body
}

// WithTableName adds the tableName to the delete segments params
func (o *DeleteSegmentsParams) WithTableName(tableName string) *DeleteSegmentsParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the delete segments params
func (o *DeleteSegmentsParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSegmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
