// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spaghettifunk/pinot-go-client/models"
)

// DeleteSegmentsReader is a Reader for the DeleteSegments structure.
type DeleteSegmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSegmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSegmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteSegmentsOK creates a DeleteSegmentsOK with default headers values
func NewDeleteSegmentsOK() *DeleteSegmentsOK {
	return &DeleteSegmentsOK{}
}

/*DeleteSegmentsOK handles this case with default header values.

successful operation
*/
type DeleteSegmentsOK struct {
	Payload *models.SuccessResponse
}

func (o *DeleteSegmentsOK) Error() string {
	return fmt.Sprintf("[POST /segments/{tableName}/delete][%d] deleteSegmentsOK  %+v", 200, o.Payload)
}

func (o *DeleteSegmentsOK) GetPayload() *models.SuccessResponse {
	return o.Payload
}

func (o *DeleteSegmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
