// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// EndReplaceSegmentsReader is a Reader for the EndReplaceSegments structure.
type EndReplaceSegmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndReplaceSegmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewEndReplaceSegmentsDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewEndReplaceSegmentsDefault creates a EndReplaceSegmentsDefault with default headers values
func NewEndReplaceSegmentsDefault(code int) *EndReplaceSegmentsDefault {
	return &EndReplaceSegmentsDefault{
		_statusCode: code,
	}
}

/*EndReplaceSegmentsDefault handles this case with default header values.

successful operation
*/
type EndReplaceSegmentsDefault struct {
	_statusCode int
}

// Code gets the status code for the end replace segments default response
func (o *EndReplaceSegmentsDefault) Code() int {
	return o._statusCode
}

func (o *EndReplaceSegmentsDefault) Error() string {
	return fmt.Sprintf("[POST /segments/{tableName}/endReplaceSegments][%d] endReplaceSegments default ", o._statusCode)
}

func (o *EndReplaceSegmentsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
