// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetConsumingSegmentsInfoParams creates a new GetConsumingSegmentsInfoParams object
// with the default values initialized.
func NewGetConsumingSegmentsInfoParams() *GetConsumingSegmentsInfoParams {
	var ()
	return &GetConsumingSegmentsInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetConsumingSegmentsInfoParamsWithTimeout creates a new GetConsumingSegmentsInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetConsumingSegmentsInfoParamsWithTimeout(timeout time.Duration) *GetConsumingSegmentsInfoParams {
	var ()
	return &GetConsumingSegmentsInfoParams{

		timeout: timeout,
	}
}

// NewGetConsumingSegmentsInfoParamsWithContext creates a new GetConsumingSegmentsInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetConsumingSegmentsInfoParamsWithContext(ctx context.Context) *GetConsumingSegmentsInfoParams {
	var ()
	return &GetConsumingSegmentsInfoParams{

		Context: ctx,
	}
}

// NewGetConsumingSegmentsInfoParamsWithHTTPClient creates a new GetConsumingSegmentsInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetConsumingSegmentsInfoParamsWithHTTPClient(client *http.Client) *GetConsumingSegmentsInfoParams {
	var ()
	return &GetConsumingSegmentsInfoParams{
		HTTPClient: client,
	}
}

/*GetConsumingSegmentsInfoParams contains all the parameters to send to the API endpoint
for the get consuming segments info operation typically these are written to a http.Request
*/
type GetConsumingSegmentsInfoParams struct {

	/*RealtimeTableName
	  Realtime table name with or without type

	*/
	RealtimeTableName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) WithTimeout(timeout time.Duration) *GetConsumingSegmentsInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) WithContext(ctx context.Context) *GetConsumingSegmentsInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) WithHTTPClient(client *http.Client) *GetConsumingSegmentsInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRealtimeTableName adds the realtimeTableName to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) WithRealtimeTableName(realtimeTableName string) *GetConsumingSegmentsInfoParams {
	o.SetRealtimeTableName(realtimeTableName)
	return o
}

// SetRealtimeTableName adds the realtimeTableName to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) SetRealtimeTableName(realtimeTableName string) {
	o.RealtimeTableName = realtimeTableName
}

// WriteToRequest writes these params to a swagger request
func (o *GetConsumingSegmentsInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param realtimeTableName
	if err := r.SetPathParam("realtimeTableName", o.RealtimeTableName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
