// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetSegmentsReader is a Reader for the GetSegments structure.
type GetSegmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSegmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSegmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSegmentsOK creates a GetSegmentsOK with default headers values
func NewGetSegmentsOK() *GetSegmentsOK {
	return &GetSegmentsOK{}
}

/*GetSegmentsOK handles this case with default header values.

successful operation
*/
type GetSegmentsOK struct {
	Payload []map[string][]string
}

func (o *GetSegmentsOK) Error() string {
	return fmt.Sprintf("[GET /segments/{tableName}][%d] getSegmentsOK  %+v", 200, o.Payload)
}

func (o *GetSegmentsOK) GetPayload() []map[string][]string {
	return o.Payload
}

func (o *GetSegmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
