// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetSegmentToCrcMapDeprecatedReader is a Reader for the GetSegmentToCrcMapDeprecated structure.
type GetSegmentToCrcMapDeprecatedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSegmentToCrcMapDeprecatedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSegmentToCrcMapDeprecatedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSegmentToCrcMapDeprecatedOK creates a GetSegmentToCrcMapDeprecatedOK with default headers values
func NewGetSegmentToCrcMapDeprecatedOK() *GetSegmentToCrcMapDeprecatedOK {
	return &GetSegmentToCrcMapDeprecatedOK{}
}

/*GetSegmentToCrcMapDeprecatedOK handles this case with default header values.

successful operation
*/
type GetSegmentToCrcMapDeprecatedOK struct {
	Payload map[string]string
}

func (o *GetSegmentToCrcMapDeprecatedOK) Error() string {
	return fmt.Sprintf("[GET /tables/{tableName}/segments/crc][%d] getSegmentToCrcMapDeprecatedOK  %+v", 200, o.Payload)
}

func (o *GetSegmentToCrcMapDeprecatedOK) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetSegmentToCrcMapDeprecatedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
