// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetConsumingSegmentsInfoReader is a Reader for the GetConsumingSegmentsInfo structure.
type GetConsumingSegmentsInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConsumingSegmentsInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetConsumingSegmentsInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetConsumingSegmentsInfoNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetConsumingSegmentsInfoInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetConsumingSegmentsInfoOK creates a GetConsumingSegmentsInfoOK with default headers values
func NewGetConsumingSegmentsInfoOK() *GetConsumingSegmentsInfoOK {
	return &GetConsumingSegmentsInfoOK{}
}

/*GetConsumingSegmentsInfoOK handles this case with default header values.

Success
*/
type GetConsumingSegmentsInfoOK struct {
}

func (o *GetConsumingSegmentsInfoOK) Error() string {
	return fmt.Sprintf("[GET /tables/{realtimeTableName}/consumingSegmentsInfo][%d] getConsumingSegmentsInfoOK ", 200)
}

func (o *GetConsumingSegmentsInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetConsumingSegmentsInfoNotFound creates a GetConsumingSegmentsInfoNotFound with default headers values
func NewGetConsumingSegmentsInfoNotFound() *GetConsumingSegmentsInfoNotFound {
	return &GetConsumingSegmentsInfoNotFound{}
}

/*GetConsumingSegmentsInfoNotFound handles this case with default header values.

Table not found
*/
type GetConsumingSegmentsInfoNotFound struct {
}

func (o *GetConsumingSegmentsInfoNotFound) Error() string {
	return fmt.Sprintf("[GET /tables/{realtimeTableName}/consumingSegmentsInfo][%d] getConsumingSegmentsInfoNotFound ", 404)
}

func (o *GetConsumingSegmentsInfoNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetConsumingSegmentsInfoInternalServerError creates a GetConsumingSegmentsInfoInternalServerError with default headers values
func NewGetConsumingSegmentsInfoInternalServerError() *GetConsumingSegmentsInfoInternalServerError {
	return &GetConsumingSegmentsInfoInternalServerError{}
}

/*GetConsumingSegmentsInfoInternalServerError handles this case with default header values.

Internal server error
*/
type GetConsumingSegmentsInfoInternalServerError struct {
}

func (o *GetConsumingSegmentsInfoInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tables/{realtimeTableName}/consumingSegmentsInfo][%d] getConsumingSegmentsInfoInternalServerError ", 500)
}

func (o *GetConsumingSegmentsInfoInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
