// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetSegmentMetadataDeprecated1Reader is a Reader for the GetSegmentMetadataDeprecated1 structure.
type GetSegmentMetadataDeprecated1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSegmentMetadataDeprecated1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSegmentMetadataDeprecated1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSegmentMetadataDeprecated1OK creates a GetSegmentMetadataDeprecated1OK with default headers values
func NewGetSegmentMetadataDeprecated1OK() *GetSegmentMetadataDeprecated1OK {
	return &GetSegmentMetadataDeprecated1OK{}
}

/*GetSegmentMetadataDeprecated1OK handles this case with default header values.

successful operation
*/
type GetSegmentMetadataDeprecated1OK struct {
	Payload [][]map[string]interface{}
}

func (o *GetSegmentMetadataDeprecated1OK) Error() string {
	return fmt.Sprintf("[GET /tables/{tableName}/segments/{segmentName}/metadata][%d] getSegmentMetadataDeprecated1OK  %+v", 200, o.Payload)
}

func (o *GetSegmentMetadataDeprecated1OK) GetPayload() [][]map[string]interface{} {
	return o.Payload
}

func (o *GetSegmentMetadataDeprecated1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
