// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSegmentToCrcMapDeprecatedParams creates a new GetSegmentToCrcMapDeprecatedParams object
// with the default values initialized.
func NewGetSegmentToCrcMapDeprecatedParams() *GetSegmentToCrcMapDeprecatedParams {
	var ()
	return &GetSegmentToCrcMapDeprecatedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSegmentToCrcMapDeprecatedParamsWithTimeout creates a new GetSegmentToCrcMapDeprecatedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSegmentToCrcMapDeprecatedParamsWithTimeout(timeout time.Duration) *GetSegmentToCrcMapDeprecatedParams {
	var ()
	return &GetSegmentToCrcMapDeprecatedParams{

		timeout: timeout,
	}
}

// NewGetSegmentToCrcMapDeprecatedParamsWithContext creates a new GetSegmentToCrcMapDeprecatedParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSegmentToCrcMapDeprecatedParamsWithContext(ctx context.Context) *GetSegmentToCrcMapDeprecatedParams {
	var ()
	return &GetSegmentToCrcMapDeprecatedParams{

		Context: ctx,
	}
}

// NewGetSegmentToCrcMapDeprecatedParamsWithHTTPClient creates a new GetSegmentToCrcMapDeprecatedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSegmentToCrcMapDeprecatedParamsWithHTTPClient(client *http.Client) *GetSegmentToCrcMapDeprecatedParams {
	var ()
	return &GetSegmentToCrcMapDeprecatedParams{
		HTTPClient: client,
	}
}

/*GetSegmentToCrcMapDeprecatedParams contains all the parameters to send to the API endpoint
for the get segment to crc map deprecated operation typically these are written to a http.Request
*/
type GetSegmentToCrcMapDeprecatedParams struct {

	/*TableName
	  Name of the table

	*/
	TableName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get segment to crc map deprecated params
func (o *GetSegmentToCrcMapDeprecatedParams) WithTimeout(timeout time.Duration) *GetSegmentToCrcMapDeprecatedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get segment to crc map deprecated params
func (o *GetSegmentToCrcMapDeprecatedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get segment to crc map deprecated params
func (o *GetSegmentToCrcMapDeprecatedParams) WithContext(ctx context.Context) *GetSegmentToCrcMapDeprecatedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get segment to crc map deprecated params
func (o *GetSegmentToCrcMapDeprecatedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get segment to crc map deprecated params
func (o *GetSegmentToCrcMapDeprecatedParams) WithHTTPClient(client *http.Client) *GetSegmentToCrcMapDeprecatedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get segment to crc map deprecated params
func (o *GetSegmentToCrcMapDeprecatedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTableName adds the tableName to the get segment to crc map deprecated params
func (o *GetSegmentToCrcMapDeprecatedParams) WithTableName(tableName string) *GetSegmentToCrcMapDeprecatedParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the get segment to crc map deprecated params
func (o *GetSegmentToCrcMapDeprecatedParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WriteToRequest writes these params to a swagger request
func (o *GetSegmentToCrcMapDeprecatedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
