// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spaghettifunk/pinot-go-client/models"
)

// ReloadSegmentReader is a Reader for the ReloadSegment structure.
type ReloadSegmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReloadSegmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReloadSegmentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewReloadSegmentOK creates a ReloadSegmentOK with default headers values
func NewReloadSegmentOK() *ReloadSegmentOK {
	return &ReloadSegmentOK{}
}

/*ReloadSegmentOK handles this case with default header values.

successful operation
*/
type ReloadSegmentOK struct {
	Payload *models.SuccessResponse
}

func (o *ReloadSegmentOK) Error() string {
	return fmt.Sprintf("[POST /segments/{tableName}/{segmentName}/reload][%d] reloadSegmentOK  %+v", 200, o.Payload)
}

func (o *ReloadSegmentOK) GetPayload() *models.SuccessResponse {
	return o.Payload
}

func (o *ReloadSegmentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
