// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewResetAllSegmentsParams creates a new ResetAllSegmentsParams object
// with the default values initialized.
func NewResetAllSegmentsParams() *ResetAllSegmentsParams {
	var ()
	return &ResetAllSegmentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewResetAllSegmentsParamsWithTimeout creates a new ResetAllSegmentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewResetAllSegmentsParamsWithTimeout(timeout time.Duration) *ResetAllSegmentsParams {
	var ()
	return &ResetAllSegmentsParams{

		timeout: timeout,
	}
}

// NewResetAllSegmentsParamsWithContext creates a new ResetAllSegmentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewResetAllSegmentsParamsWithContext(ctx context.Context) *ResetAllSegmentsParams {
	var ()
	return &ResetAllSegmentsParams{

		Context: ctx,
	}
}

// NewResetAllSegmentsParamsWithHTTPClient creates a new ResetAllSegmentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewResetAllSegmentsParamsWithHTTPClient(client *http.Client) *ResetAllSegmentsParams {
	var ()
	return &ResetAllSegmentsParams{
		HTTPClient: client,
	}
}

/*ResetAllSegmentsParams contains all the parameters to send to the API endpoint
for the reset all segments operation typically these are written to a http.Request
*/
type ResetAllSegmentsParams struct {

	/*MaxWaitTimeMs
	  Maximum time in milliseconds to wait for reset to be completed. By default, uses serverAdminRequestTimeout

	*/
	MaxWaitTimeMs *int64
	/*TableNameWithType
	  Name of the table with type

	*/
	TableNameWithType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the reset all segments params
func (o *ResetAllSegmentsParams) WithTimeout(timeout time.Duration) *ResetAllSegmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reset all segments params
func (o *ResetAllSegmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reset all segments params
func (o *ResetAllSegmentsParams) WithContext(ctx context.Context) *ResetAllSegmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reset all segments params
func (o *ResetAllSegmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reset all segments params
func (o *ResetAllSegmentsParams) WithHTTPClient(client *http.Client) *ResetAllSegmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reset all segments params
func (o *ResetAllSegmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMaxWaitTimeMs adds the maxWaitTimeMs to the reset all segments params
func (o *ResetAllSegmentsParams) WithMaxWaitTimeMs(maxWaitTimeMs *int64) *ResetAllSegmentsParams {
	o.SetMaxWaitTimeMs(maxWaitTimeMs)
	return o
}

// SetMaxWaitTimeMs adds the maxWaitTimeMs to the reset all segments params
func (o *ResetAllSegmentsParams) SetMaxWaitTimeMs(maxWaitTimeMs *int64) {
	o.MaxWaitTimeMs = maxWaitTimeMs
}

// WithTableNameWithType adds the tableNameWithType to the reset all segments params
func (o *ResetAllSegmentsParams) WithTableNameWithType(tableNameWithType string) *ResetAllSegmentsParams {
	o.SetTableNameWithType(tableNameWithType)
	return o
}

// SetTableNameWithType adds the tableNameWithType to the reset all segments params
func (o *ResetAllSegmentsParams) SetTableNameWithType(tableNameWithType string) {
	o.TableNameWithType = tableNameWithType
}

// WriteToRequest writes these params to a swagger request
func (o *ResetAllSegmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.MaxWaitTimeMs != nil {

		// query param maxWaitTimeMs
		var qrMaxWaitTimeMs int64
		if o.MaxWaitTimeMs != nil {
			qrMaxWaitTimeMs = *o.MaxWaitTimeMs
		}
		qMaxWaitTimeMs := swag.FormatInt64(qrMaxWaitTimeMs)
		if qMaxWaitTimeMs != "" {
			if err := r.SetQueryParam("maxWaitTimeMs", qMaxWaitTimeMs); err != nil {
				return err
			}
		}

	}

	// path param tableNameWithType
	if err := r.SetPathParam("tableNameWithType", o.TableNameWithType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
