// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UploadSegmentAsMultiPartReader is a Reader for the UploadSegmentAsMultiPart structure.
type UploadSegmentAsMultiPartReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadSegmentAsMultiPartReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewUploadSegmentAsMultiPartDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewUploadSegmentAsMultiPartDefault creates a UploadSegmentAsMultiPartDefault with default headers values
func NewUploadSegmentAsMultiPartDefault(code int) *UploadSegmentAsMultiPartDefault {
	return &UploadSegmentAsMultiPartDefault{
		_statusCode: code,
	}
}

/*UploadSegmentAsMultiPartDefault handles this case with default header values.

successful operation
*/
type UploadSegmentAsMultiPartDefault struct {
	_statusCode int
}

// Code gets the status code for the upload segment as multi part default response
func (o *UploadSegmentAsMultiPartDefault) Code() int {
	return o._statusCode
}

func (o *UploadSegmentAsMultiPartDefault) Error() string {
	return fmt.Sprintf("[POST /segments][%d] uploadSegmentAsMultiPart default ", o._statusCode)
}

func (o *UploadSegmentAsMultiPartDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
