// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteClusterConfigReader is a Reader for the DeleteClusterConfig structure.
type DeleteClusterConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteClusterConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteClusterConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewDeleteClusterConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteClusterConfigOK creates a DeleteClusterConfigOK with default headers values
func NewDeleteClusterConfigOK() *DeleteClusterConfigOK {
	return &DeleteClusterConfigOK{}
}

/*DeleteClusterConfigOK handles this case with default header values.

Success
*/
type DeleteClusterConfigOK struct {
}

func (o *DeleteClusterConfigOK) Error() string {
	return fmt.Sprintf("[DELETE /cluster/configs/{configName}][%d] deleteClusterConfigOK ", 200)
}

func (o *DeleteClusterConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteClusterConfigInternalServerError creates a DeleteClusterConfigInternalServerError with default headers values
func NewDeleteClusterConfigInternalServerError() *DeleteClusterConfigInternalServerError {
	return &DeleteClusterConfigInternalServerError{}
}

/*DeleteClusterConfigInternalServerError handles this case with default header values.

Server error deleting configuration
*/
type DeleteClusterConfigInternalServerError struct {
}

func (o *DeleteClusterConfigInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /cluster/configs/{configName}][%d] deleteClusterConfigInternalServerError ", 500)
}

func (o *DeleteClusterConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
