// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetClusterInfoReader is a Reader for the GetClusterInfo structure.
type GetClusterInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClusterInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetClusterInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetClusterInfoInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetClusterInfoOK creates a GetClusterInfoOK with default headers values
func NewGetClusterInfoOK() *GetClusterInfoOK {
	return &GetClusterInfoOK{}
}

/*GetClusterInfoOK handles this case with default header values.

Success
*/
type GetClusterInfoOK struct {
}

func (o *GetClusterInfoOK) Error() string {
	return fmt.Sprintf("[GET /cluster/info][%d] getClusterInfoOK ", 200)
}

func (o *GetClusterInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetClusterInfoInternalServerError creates a GetClusterInfoInternalServerError with default headers values
func NewGetClusterInfoInternalServerError() *GetClusterInfoInternalServerError {
	return &GetClusterInfoInternalServerError{}
}

/*GetClusterInfoInternalServerError handles this case with default header values.

Internal server error
*/
type GetClusterInfoInternalServerError struct {
}

func (o *GetClusterInfoInternalServerError) Error() string {
	return fmt.Sprintf("[GET /cluster/info][%d] getClusterInfoInternalServerError ", 500)
}

func (o *GetClusterInfoInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
