// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ListClusterConfigsReader is a Reader for the ListClusterConfigs structure.
type ListClusterConfigsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListClusterConfigsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListClusterConfigsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListClusterConfigsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListClusterConfigsOK creates a ListClusterConfigsOK with default headers values
func NewListClusterConfigsOK() *ListClusterConfigsOK {
	return &ListClusterConfigsOK{}
}

/*ListClusterConfigsOK handles this case with default header values.

Success
*/
type ListClusterConfigsOK struct {
}

func (o *ListClusterConfigsOK) Error() string {
	return fmt.Sprintf("[GET /cluster/configs][%d] listClusterConfigsOK ", 200)
}

func (o *ListClusterConfigsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListClusterConfigsInternalServerError creates a ListClusterConfigsInternalServerError with default headers values
func NewListClusterConfigsInternalServerError() *ListClusterConfigsInternalServerError {
	return &ListClusterConfigsInternalServerError{}
}

/*ListClusterConfigsInternalServerError handles this case with default header values.

Internal server error
*/
type ListClusterConfigsInternalServerError struct {
}

func (o *ListClusterConfigsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /cluster/configs][%d] listClusterConfigsInternalServerError ", 500)
}

func (o *ListClusterConfigsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
