// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateClusterConfigReader is a Reader for the UpdateClusterConfig structure.
type UpdateClusterConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateClusterConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateClusterConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewUpdateClusterConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateClusterConfigOK creates a UpdateClusterConfigOK with default headers values
func NewUpdateClusterConfigOK() *UpdateClusterConfigOK {
	return &UpdateClusterConfigOK{}
}

/*UpdateClusterConfigOK handles this case with default header values.

Success
*/
type UpdateClusterConfigOK struct {
}

func (o *UpdateClusterConfigOK) Error() string {
	return fmt.Sprintf("[POST /cluster/configs][%d] updateClusterConfigOK ", 200)
}

func (o *UpdateClusterConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateClusterConfigInternalServerError creates a UpdateClusterConfigInternalServerError with default headers values
func NewUpdateClusterConfigInternalServerError() *UpdateClusterConfigInternalServerError {
	return &UpdateClusterConfigInternalServerError{}
}

/*UpdateClusterConfigInternalServerError handles this case with default header values.

Server error updating configuration
*/
type UpdateClusterConfigInternalServerError struct {
}

func (o *UpdateClusterConfigInternalServerError) Error() string {
	return fmt.Sprintf("[POST /cluster/configs][%d] updateClusterConfigInternalServerError ", 500)
}

func (o *UpdateClusterConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
