// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SegmentSizeInfo segment size info
//
// swagger:model SegmentSizeInfo
type SegmentSizeInfo struct {

	// disk size in bytes
	DiskSizeInBytes int64 `json:"diskSizeInBytes,omitempty"`

	// segment name
	SegmentName string `json:"segmentName,omitempty"`
}

// Validate validates this segment size info
func (m *SegmentSizeInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SegmentSizeInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SegmentSizeInfo) UnmarshalBinary(b []byte) error {
	var res SegmentSizeInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
